import type { Track, Album, CuratorIssue, RadioStation } from '../types/music';

// Verified, reliable, fast-streaming royalty-free / Creative Commons audio CDN tracks
export const CURATED_TRACKS: Track[] = [
  {
    id: 'aura-01',
    title: 'Kinetic Stillness (Modular Tape Study #4)',
    artist: 'Holloway & The Monolith',
    album: 'Frequencies for Solitude',
    duration: 218,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=ambient-piano-amp-strings-10711.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    bpm: 68,
    musicalKey: 'D Minor',
    genre: 'Ambient',
    mood: 'Late Night',
    tags: ['Tape Decay', 'Modular Synth', 'Reverb', 'Warm Analog'],
    curatorNote: 'Recorded on a restored Revox B77 1/4" tape machine in an abandoned textile mill near Sheffield. The tape hiss is preserved as a harmonic layer.',
    storyQuote: '“Silence is not an absence of sound, but the space where subtle textures finally breathe.”',
    releaseDate: '2025-01-14',
    license: 'CC BY-NC 4.0',
    waveform: [12, 18, 25, 40, 60, 75, 82, 90, 70, 55, 48, 62, 80, 95, 88, 65, 45, 30, 22, 15],
    playsCount: 14200,
  },
  {
    id: 'aura-02',
    title: 'Paper Architecture & Rain',
    artist: 'Kaito Moriyama',
    album: 'Architectural Blueprints in Ash',
    duration: 184,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=lofi-study-112191.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop',
    bpm: 74,
    musicalKey: 'F Major',
    genre: 'Lo-Fi',
    mood: 'Deep Focus',
    tags: ['Dusty Keys', 'Tokyo Rain', 'Felt Piano', 'Subtle Foley'],
    curatorNote: 'Moriyama captures the quiet geometry of Tokyo dusk with muted felt piano hammers and field recordings from Yoyogi Park under light precipitation.',
    storyQuote: '“A rhythmic study for pencils on tracing paper and warm tea cooling slowly.”',
    releaseDate: '2024-11-20',
    license: 'CC BY-SA 4.0',
    waveform: [30, 45, 50, 65, 70, 68, 72, 85, 90, 84, 76, 60, 55, 68, 74, 52, 40, 35, 28, 20],
    playsCount: 28940,
  },
  {
    id: 'aura-03',
    title: 'Nocturne for Two Cellos & Sub-Bass',
    artist: 'Elena Rostova & Ensemble',
    album: 'Resonance in Granite',
    duration: 245,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c0780287.mp3?filename=reflected-light-147979.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?q=80&w=800&auto=format&fit=crop',
    bpm: 62,
    musicalKey: 'A Minor',
    genre: 'Neo-Classical',
    mood: 'Melancholic',
    tags: ['Chamber', 'Deep Bowing', 'Acoustic Resonance', 'Sub Harmonics'],
    curatorNote: 'Arranged for two vintage Italian cellos paired with a sub-bass sine wave tuned to 43.6 Hz. Mastered directly for high-impedance headphones.',
    storyQuote: '“Strings stretched to the threshold of breaking, holding back a storm of low frequencies.”',
    releaseDate: '2025-02-02',
    license: 'CC BY-NC-ND 4.0',
    waveform: [15, 22, 38, 55, 78, 88, 92, 85, 72, 60, 68, 82, 94, 100, 85, 62, 40, 28, 18, 10],
    playsCount: 19500,
  },
  {
    id: 'aura-04',
    title: 'Signal to Horizon (North Sea Drift)',
    artist: 'Søren Lindqvist',
    album: 'Frequencies for Solitude',
    duration: 312,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=floating-abstract-142819.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    bpm: 82,
    musicalKey: 'C Minor',
    genre: 'Downtempo',
    mood: 'Ethereal',
    tags: ['Nordic', 'Analog Synth', 'Glacial Drone', 'Tape Loops'],
    curatorNote: 'Recorded in a decommissioned lighthouse on the Jutland coast. Echoes of modular synthesizers bouncing off saltwater-dampened concrete walls.',
    storyQuote: '“Where the cold salt mist meets vintage circuitry.”',
    releaseDate: '2024-10-18',
    license: 'CC BY 4.0',
    waveform: [20, 32, 44, 60, 70, 80, 75, 65, 58, 62, 78, 85, 90, 82, 70, 50, 42, 30, 20, 14],
    playsCount: 31200,
  },
  {
    id: 'aura-05',
    title: 'Blue Hour in Kyoto (Shinkansen Delay)',
    artist: 'Tatsuo Hoshino Trio',
    album: 'Midnight Metro Variations',
    duration: 260,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/02/07/audio_d19a4e9b98.mp3?filename=chill-abstract-intention-12099.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    bpm: 88,
    musicalKey: 'E♭ Major',
    genre: 'Jazz Fusion',
    mood: 'Warm & Analog',
    tags: ['Rhodes MK II', 'Upright Bass', 'Brushed Snare', 'Nocturne'],
    curatorNote: 'An improvisational suite tracked in one take on vintage Neumann U67 microphones. The Rhodes piano has slight tube saturation.',
    storyQuote: '“Neon reflections in train windows as midnight approaches Kyoto station.”',
    releaseDate: '2024-12-05',
    license: 'CC BY-NC 4.0',
    waveform: [35, 48, 62, 75, 80, 85, 78, 88, 92, 80, 70, 75, 84, 88, 76, 62, 48, 38, 25, 18],
    playsCount: 42100,
  },
  {
    id: 'aura-06',
    title: 'Sub-Zero Resonance',
    artist: 'Alva & The Grid',
    album: 'Monolith: Minimal Works',
    duration: 198,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/26/audio_d0c6ff1101.mp3?filename=electronic-future-beats-117997.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=800&auto=format&fit=crop',
    bpm: 110,
    musicalKey: 'G Minor',
    genre: 'Electronic',
    mood: 'Hypnotic',
    tags: ['Berlin School', 'Analogue Pulse', 'Sub Bass', 'Minimal Techno'],
    curatorNote: 'Precision-carved rhythmic pulses created entirely on an analog Buchla 200e modular system. Zero software quantization.',
    storyQuote: '“Mathematical pulses designed for dark rooms and focused minds.”',
    releaseDate: '2025-01-30',
    license: 'CC BY-SA 4.0',
    waveform: [40, 60, 80, 95, 85, 90, 95, 88, 92, 98, 90, 85, 92, 96, 88, 75, 60, 45, 30, 20],
    playsCount: 22800,
  },
  {
    id: 'aura-07',
    title: 'Felt Hammer Studies in C',
    artist: 'Nils Vance',
    album: 'Intimate Acoustics Vol. II',
    duration: 215,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/16/audio_c68c34bb99.mp3?filename=sad-piano-ambient-111424.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1520523839898-5071282543e1?q=80&w=800&auto=format&fit=crop',
    bpm: 56,
    musicalKey: 'C Major',
    genre: 'Minimalism',
    mood: 'Meditative',
    tags: ['Muted Felt', 'Upright Piano', 'Pedal Creaks', 'Intimate'],
    curatorNote: 'The felt dampers were doubled in thickness to eliminate high overtones. Listen closely for the mechanical breath of the wooden pedal mechanism.',
    storyQuote: '“Music not meant to demand attention, but to keep company with solitude.”',
    releaseDate: '2025-02-10',
    license: 'CC BY 4.0',
    waveform: [10, 25, 45, 60, 72, 80, 65, 50, 40, 55, 70, 85, 78, 62, 45, 30, 20, 15, 10, 8],
    playsCount: 16700,
  },
  {
    id: 'aura-08',
    title: 'Concrete Shadows & Brass',
    artist: 'The Baltic Collective',
    album: 'Brutalist Suites',
    duration: 280,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2021/08/04/audio_12b0c7443c.mp3?filename=cinematic-ambient-115349.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    bpm: 72,
    musicalKey: 'B Minor',
    genre: 'Post-Rock',
    mood: 'Urban Drift',
    tags: ['Muted French Horn', 'Reverberant Hall', 'Granular Bass', 'Slow Burn'],
    curatorNote: 'Commissioned for the architectural retrospective on brutalist structures of Eastern Europe. Pure acoustic grandeur.',
    storyQuote: '“Heavy materials rendered weightless through harmonic overtones.”',
    releaseDate: '2024-09-12',
    license: 'CC BY-NC 4.0',
    waveform: [18, 30, 48, 65, 78, 85, 92, 90, 82, 88, 96, 100, 92, 80, 65, 48, 35, 22, 14, 10],
    playsCount: 13400,
  },
  {
    id: 'aura-09',
    title: 'Trans-Eurasian Night Express',
    artist: 'Vera Chen & Orbital Mechanics',
    album: 'Midnight Metro Variations',
    duration: 232,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/03/24/audio_c3b520cfc3.mp3?filename=lofi-study-112191.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
    bpm: 94,
    musicalKey: 'G# Minor',
    genre: 'Lo-Fi',
    mood: 'Late Night',
    tags: ['Night Train', 'Tape Saturated Chords', 'Sidechain Pulse', 'Vinyl Crackle'],
    curatorNote: 'Captures the hypnotic metallic rhythm of steel rails crossing vast Eurasian steppes under starless skies.',
    storyQuote: '“The steady lullaby of wheels against tracks while the carriage sleeps.”',
    releaseDate: '2024-12-14',
    license: 'CC BY-SA 4.0',
    waveform: [28, 42, 58, 68, 75, 82, 88, 84, 78, 80, 86, 90, 82, 74, 60, 46, 34, 24, 18, 12],
    playsCount: 34500,
  },
  {
    id: 'aura-10',
    title: 'Granular Clouds over Oshima',
    artist: 'Hiroshi Takahashi',
    album: 'Frequencies for Solitude',
    duration: 275,
    audioUrl: 'https://cdn.pixabay.com/download/audio/2022/11/06/audio_c0c329d290.mp3?filename=ambient-soundscape-124976.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=800&auto=format&fit=crop',
    bpm: 50,
    musicalKey: 'F# Minor',
    genre: 'Ambient',
    mood: 'Meditative',
    tags: ['Granular Synthesis', 'Volcanic Soil', 'Pacific Ocean', 'Wind Harps'],
    curatorNote: 'Takahashi fed acoustic recordings of wind across volcanic crater ridges into a granular synthesis patch running on Max/MSP.',
    storyQuote: '“Erosion transformed into long-form frequency decay.”',
    releaseDate: '2025-01-05',
    license: 'CC BY 4.0',
    waveform: [10, 18, 30, 48, 62, 70, 78, 85, 80, 72, 68, 75, 82, 78, 65, 50, 35, 22, 14, 8],
    playsCount: 21900,
  }
];

export const CURATED_ALBUMS: Album[] = [
  {
    id: 'album-01',
    title: 'Frequencies for Solitude',
    artist: 'Holloway, Lindqvist & Takahashi',
    year: '2025',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    genre: 'Ambient',
    label: 'Aura Sound Editions (ASE-08)',
    bpmRange: '50 – 82 BPM',
    totalDuration: '14 min',
    recordingLocation: 'Sheffield, Jutland & Izu Oshima',
    curatorEssay: 'A tri-continental collaboration exploring the acoustic phenomenology of isolation. Utilizing 1/4" tape loops, coastal field recordings, and granular synthesis, the record serves as an acoustic sanctuary from modern digital noise.',
    tracks: [
      CURATED_TRACKS[0],
      CURATED_TRACKS[3],
      CURATED_TRACKS[9],
    ]
  },
  {
    id: 'album-02',
    title: 'Midnight Metro Variations',
    artist: 'Tatsuo Hoshino Trio & Vera Chen',
    year: '2024',
    coverUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    genre: 'Jazz Fusion',
    label: 'Nocturne Dispatches',
    bpmRange: '88 – 94 BPM',
    totalDuration: '12 min',
    recordingLocation: 'Kyoto & Ulaanbaatar Train Car 4',
    curatorEssay: 'Born from late-night commuter observations in Tokyo and long trans-continental sleeper trains. Features vintage electric pianos running through custom analog spring reverbs.',
    tracks: [
      CURATED_TRACKS[4],
      CURATED_TRACKS[8],
      CURATED_TRACKS[1],
    ]
  },
  {
    id: 'album-03',
    title: 'Resonance in Granite',
    artist: 'Elena Rostova & Ensemble',
    year: '2025',
    coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?q=80&w=800&auto=format&fit=crop',
    genre: 'Neo-Classical',
    label: 'Monolith Chamber Series',
    bpmRange: '56 – 72 BPM',
    totalDuration: '15 min',
    recordingLocation: 'Granite Quarry Hall, Tampere',
    curatorEssay: 'Recorded inside a decommissioned stone quarry with 6-second natural acoustic reverberation. Acoustic wooden instruments collide with subterranean sine waves.',
    tracks: [
      CURATED_TRACKS[2],
      CURATED_TRACKS[6],
      CURATED_TRACKS[7],
    ]
  },
  {
    id: 'album-04',
    title: 'Monolith: Minimal Works',
    artist: 'Alva & The Grid',
    year: '2025',
    coverUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=800&auto=format&fit=crop',
    genre: 'Electronic',
    label: 'Buchla Laboratory Berlin',
    bpmRange: '110 BPM',
    totalDuration: '10 min',
    recordingLocation: 'Studio Kreuzberg, Berlin',
    curatorEssay: 'An exercise in absolute hardware constraint. No computers were used during tracking or mixing; all triggers originated from custom voltage clocks.',
    tracks: [
      CURATED_TRACKS[5],
      CURATED_TRACKS[0],
      CURATED_TRACKS[3],
    ]
  }
];

export const CURRENT_ISSUE: CuratorIssue = {
  id: 'issue-14',
  issueNumber: 14,
  seasonYear: 'Winter / Spring 2026',
  title: 'Textures of the Subconscious',
  subtitle: 'The Renaissance of Tactile Tape, Deep Sub-Bass & Intimate Room Acoustics',
  curatorName: 'Dr. Maeve Vance',
  curatorRole: 'Editor in Chief & Sonic Archaeologist',
  curatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
  coverHeroUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop',
  leadArticle: `In an era defined by compressed streaming codecs and disposable digital feeds, a quiet counter-revolution has taken root. Across basement studios in Berlin, abandoned textile lofts in Northern England, and tea houses in Kyoto, composers are returning to physical decay—magnetic tape hysteresis, felt-dampened hammer acoustics, and the deep subterranean hum of analogue circuitry.

Issue #14 examines how physical constraint restores meaning to sound. When a recording captures the mechanical creak of a wooden sustain pedal or the gentle hiss of iron oxide drifting across a playback head, it establishes a communion between human hands and acoustic space that algorithmic algorithms can never simulate.

Put on your finest headphones, dim the room, and let these selections unfold at their own deliberate tempo.`,
  featuredTracks: [
    CURATED_TRACKS[0],
    CURATED_TRACKS[2],
    CURATED_TRACKS[4],
    CURATED_TRACKS[1],
  ],
  spotlightArtist: {
    name: 'Holloway & The Monolith',
    bio: 'Composer and tape archivist working out of Sheffield, UK. Known for weaving vintage 1970s analog tape machines with contemporary modular synthesis.',
    location: 'Sheffield, United Kingdom',
    quote: '“We do not clean up the background noise because the background noise is the room where you were sitting when you felt it.”',
    artworkUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
  },
  sonicThemes: [
    {
      title: 'Tape Hiss & Analog Decay',
      description: 'Recordings that celebrate the texture and warmth of magnetic oxide ribbon.',
      trackIds: ['aura-01', 'aura-04', 'aura-09'],
    },
    {
      title: 'Acoustic Architecture',
      description: 'Chamber instruments recorded in resonant granite halls and damp stone chambers.',
      trackIds: ['aura-03', 'aura-07', 'aura-08'],
    },
    {
      title: 'Midnight Commutes',
      description: 'Downtempo suites for empty train carriages and neon-streaked highway rain.',
      trackIds: ['aura-02', 'aura-05', 'aura-06'],
    }
  ]
};

export const RADIO_STATIONS: RadioStation[] = [
  {
    id: 'station-01',
    name: 'Kyoto Rain & Rhodes',
    tagline: 'Warm electric pianos, gentle tape decay, and night-shift melodies.',
    description: 'A continuous stream for deep coding, late-night reading, and quiet contemplation.',
    mood: 'Late Night',
    coverUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    curator: 'Tatsuo Hoshino',
    frequencies: '94.2 MHz FM (Kyoto Audio Lab)',
    tracks: [CURATED_TRACKS[1], CURATED_TRACKS[4], CURATED_TRACKS[8], CURATED_TRACKS[0]],
  },
  {
    id: 'station-02',
    name: 'Nordic Glacial Drift',
    tagline: 'Vast analog synth drones and oceanic sub-bass.',
    description: 'Slow-evolving soundscapes engineered for deep meditative focus and spatial calm.',
    mood: 'Deep Focus',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
    curator: 'Søren Lindqvist',
    frequencies: '88.7 MHz FM (Copenhagen Archive)',
    tracks: [CURATED_TRACKS[3], CURATED_TRACKS[0], CURATED_TRACKS[9], CURATED_TRACKS[2]],
  },
  {
    id: 'station-03',
    name: 'Brutalist Monolith',
    tagline: 'Analogue Buchla clock pulses and subterranean bass harmonics.',
    description: 'Rigorous architectural rhythms with tactile physical momentum.',
    mood: 'Hypnotic',
    coverUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=800&auto=format&fit=crop',
    curator: 'Alva & The Grid',
    frequencies: '101.4 MHz FM (Berlin Studio)',
    tracks: [CURATED_TRACKS[5], CURATED_TRACKS[7], CURATED_TRACKS[3], CURATED_TRACKS[0]],
  },
  {
    id: 'station-04',
    name: 'Felt & Chamber Silence',
    tagline: 'Muted upright pianos and intimate cello overtones.',
    description: 'Chamber minimalism where every creak and breath becomes part of the music.',
    mood: 'Meditative',
    coverUrl: 'https://images.unsplash.com/photo-1520523839898-5071282543e1?q=80&w=800&auto=format&fit=crop',
    curator: 'Elena Rostova',
    frequencies: '96.1 MHz FM (Tampere Hall)',
    tracks: [CURATED_TRACKS[6], CURATED_TRACKS[2], CURATED_TRACKS[1], CURATED_TRACKS[7]],
  }
];
